swiss_airline_policy_rag:
  unstructured_docs: "data/unstructured_docs/swiss_airline_policy"
  vectordb: "data/airline_policy_vectordb"
  collection_name: rag-chroma
  llm: gpt-4o-mini
  llm_temperature: 0.0
  embedding_model: text-embedding-3-small
  chunk_size: 500
  chunk_overlap: 100
  k: 2
